version: 2
machine:
  environment:
jobs:
  deploy:
    docker:
      - image: circleci/node:9.8.0
        environment:
          PROJECT_NAME: wire-bot
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and deploy application
          command: chmod +x .circleci/deploy.sh && .circleci/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - staging


