version: 2
machine:
  environment:
jobs:
  test:
      docker:
        - image: circleci/node:9.8.0
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Install packages
            command: npm i
        - run:
            name: Run tests
            command: npm test
  deploy:
    docker:
      - image: circleci/node:9.8.0
        environment:
          PROJECT_NAME: wire-bot
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: Build and deploy application
        command: chmod +x .circleci/deploy.sh && .circleci/deploy.sh
workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
        requires:
          - test
        filters:
          branches:
            only:
              - master
              - staging


